version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:5.6-alpine
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - HTTP_EXPOSE=9200
