name: Run tests
on: [push]

env:
  ES_VERSION: 7.17.1


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run elasticsearch
        run: wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${{ ES_VERSION }}.tar.gz && tar -xvf elasticsearch-${{ ES_VERSION }}.tar.gz && elasticsearch-${{ ES_VERSION }}/bin/elasticsearch
      - name: Run tests
        run: vendor/bin/phpunit tests
